---
title: Publats Marítims
timezone: Europe/Madrid
collections:
  cafes:
    title: Cafes
    output: true
    permalink: "/:collection/:name"
    label: cafes
  posts:
    title: Posts
    output: true
  pubs:
    title: Bars
    output: true
    permalink: "/:collection/:name"
    label: bars
  restaurants:
    title: Restaurants
    output: true
    permalink: "/:collection/:name"
    label: restaurants
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pubs
  values:
    layout: post
- scope:
    path: ''
    type: cafes
  values:
    layout: post
- scope:
    path: ''
    type: restaurants
  values:
    layout: post
author:
  name: Luke Rice
  email: lukeychops@hotmail.com
description: 'Silly reviews of (some of) the bars, cafes and restaurants in Poblats
  Marítims – Valencia from people who live, drink and eat in the area. Click ‘reviews’
  in the menu tab for a list, on ‘map’ for uummm a map or on the ‘categories’ drop-down
  menu.

'
show_excerpts: false
minima:
  date_format: "%b %-d, %Y"
theme: minima
plugins:
- jekyll-seo-tag
